/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package LoginPage;
import javax.swing.*;
import WeatherReport.*;
import IrrigationAndFertilizerAdvisor.*;
import CropRecommender.*;
/**
 *
 * @author skysm
 */
public class HomePage extends javax.swing.JFrame {
    
    private String username;
    /**
     * Creates new form HomePage
     */
    public HomePage(String uname) {
        initComponents();
        welcomeLabel.setText("Welcome "+username+"!");
        setLocationRelativeTo(null);
        username = uname;
        
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        btnweatherinfo = new javax.swing.JButton();
        btnirrigation = new javax.swing.JButton();
        btnfertilizer = new javax.swing.JButton();
        btncroprecommender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcomeLabel.setText("Welcome");

        btnweatherinfo.setText("Weather info");
        btnweatherinfo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnweatherinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnweatherinfoActionPerformed(evt);
            }
        });

        btnirrigation.setText("Irrigation advisor");
        btnirrigation.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnirrigation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnirrigationActionPerformed(evt);
            }
        });

        btnfertilizer.setText("Fertilizer advisor");
        btnfertilizer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfertilizerActionPerformed(evt);
            }
        });

        btncroprecommender.setText("Crop recommender");
        btncroprecommender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncroprecommenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnweatherinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnirrigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnfertilizer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btncroprecommender, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(121, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(welcomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(welcomeLabel)
                .addGap(97, 97, 97)
                .addComponent(btnweatherinfo)
                .addGap(36, 36, 36)
                .addComponent(btnirrigation)
                .addGap(40, 40, 40)
                .addComponent(btnfertilizer)
                .addGap(40, 40, 40)
                .addComponent(btncroprecommender)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnweatherinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnweatherinfoActionPerformed
        // TODO add your handling code here:
        WeatherInfo wi = new WeatherInfo(username);
        wi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnweatherinfoActionPerformed

    private void btnfertilizerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfertilizerActionPerformed
        // TODO add your handling code here:
        FertilizerAdvisor fa = new FertilizerAdvisor(username);
        fa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnfertilizerActionPerformed

    private void btnirrigationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnirrigationActionPerformed
        // TODO add your handling code here:
        IrrigationAdvisor ia = new IrrigationAdvisor(username);
        ia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnirrigationActionPerformed

    private void btncroprecommenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncroprecommenderActionPerformed
        // TODO add your handling code here:
        CropRecommender cr = new CropRecommender(username);
        cr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btncroprecommenderActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncroprecommender;
    private javax.swing.JButton btnfertilizer;
    private javax.swing.JButton btnirrigation;
    private javax.swing.JButton btnweatherinfo;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
